#!/bin/bash
# Apply pywal colors to Kitty terminal
# This script applies the colors generated by WallRizz/pywal to Kitty

# Check if pywal colors exist
if [ ! -f ~/.cache/wal/colors.json ]; then
    echo "Error: Pywal colors not found. Run WallRizz first."
    exit 1
fi

# Extract colors from pywal
bg=$(jq -r '.special.background' ~/.cache/wal/colors.json)
fg=$(jq -r '.special.foreground' ~/.cache/wal/colors.json)
cursor=$(jq -r '.special.cursor' ~/.cache/wal/colors.json)

# Extract the 16 colors
colors=($(jq -r '.colors | to_entries[] | .value' ~/.cache/wal/colors.json))

# Create kitty color config
cat > ~/.config/kitty/pywal_colors.conf << EOF
# Pywal colors for Kitty
# Generated from WallRizz wallpaper colors

foreground ${fg}
background ${bg}
cursor ${cursor}

# Black
color0 ${colors[0]}
color8 ${colors[8]}

# Red
color1 ${colors[1]}
color9 ${colors[9]}

# Green
color2 ${colors[2]}
color10 ${colors[10]}

# Yellow
color3 ${colors[3]}
color11 ${colors[11]}

# Blue
color4 ${colors[4]}
color12 ${colors[12]}

# Magenta
color5 ${colors[5]}
color13 ${colors[13]}

# Cyan
color6 ${colors[6]}
color14 ${colors[14]}

# White
color7 ${colors[7]}
color15 ${colors[15]}

# Selection colors
selection_foreground ${bg}
selection_background ${fg}

# URL color
url_color ${colors[4]}
EOF

# Include the color config in main kitty.conf if not already included
if ! grep -q "include pywal_colors.conf" ~/.config/kitty/kitty.conf; then
    echo "" >> ~/.config/kitty/kitty.conf
    echo "# Include pywal colors (updated by WallRizz)" >> ~/.config/kitty/kitty.conf
    echo "include pywal_colors.conf" >> ~/.config/kitty/kitty.conf
fi

echo "Kitty theme updated with pywal colors!"
echo "Colors extracted from: $(jq -r '.wallpaper' ~/.cache/wal/colors.json 2>/dev/null || echo 'WallRizz wallpaper')"

# Try to reload kitty if it's running
if pgrep -x kitty > /dev/null; then
    echo "Attempting to reload Kitty colors..."
    kitty @ load-config || echo "Note: Restart Kitty to see new colors"
fi
